name: ethiomotion_words
description: "EthioMotion Words - A Heads Up style game with Ethiopian theme"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^7.0.0
  google_fonts: ^8.0.2
  provider: ^6.1.5+1
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/words/ethiopian_food.json
    - assets/words/ethiopian_cities.json
    - assets/words/ethiopian_celebrities.json
    - assets/words/ethiopian_history.json
    - assets/words/animals.json
    - assets/words/general_fun_words.json
